title: Manrique Vargas # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Urban Data Science & Engineering
  <br><br>
  Manrique earned his master's degree at NYU CUSP with a focus in using data science techniques to foster sustainable development. 
  He previously graduated from the University of Hong Kong with a degree in engineering, and has industry experience in data analysis, numerical modeling, and remote sensing. 
  <br><br>
  <a href="https://www.linkedin.com/in/manrique-vargas/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-146769424-1 # your Google Analytics tracking ID here
