title: Manrique Vargas # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science & Engineering
  <br><br>
  <br><br>
  
  <a href="https://www.linkedin.com/in/manriq/">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-146769424-1 # your Google Analytics tracking ID here
