title: Manrique Vargas # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Urban Data Science & Engineering
  <br><br>
  Manrique has a master's degree in urban science and a bachelor in engineering, and has industry experience in data analysis, numerical modeling, and remote sensing. 
  He uses data science techniques to foster sustainable development. 
  <br><br>
  <a href="https://www.linkedin.com/in/manrique-vargas/">View My LinkedIn Profile</a> 
  
#theme: jekyll-theme-minimal
google_analytics: UA-146769424-1 # your Google Analytics tracking ID here
